<?php

/**
 * @file
 * Installation functions for Lorem ipsum module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function poc_install() {
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, [
    'view kaomoji' => TRUE,
    'generate token' => TRUE,
  ]);

  user_role_change_permissions(RoleInterface::ANONYMOUS_ID, [
    'view kaomoji' => TRUE,
    'generate token' => TRUE,
  ]);
}
