poc.settings:
  type: config_object
  label: 'Token Generator settings'
  mapping:
    poc:
      type: mapping
      mapping:
        tokenAlphabet:
          type: text
          label: 'String of which the Token Generator can choose characters from.'
        KaomojiApp:
          type: boolean
          label: 'Use the VueJS app instead of a static block.'

block.settings.poc_block:
  type: block_settings
  label: 'Lorem ipsum block'
  mapping:
    poc_block_settings:
      type: text
      label: 'Lorem ipsum block settings'
