poc.settings:
  type: config_object
  label: 'Token Generator settings'
  mapping:
    poc:
      type: mapping
      mapping:
        tokenLength:
          type: integer
          label: 'Decides how long the generated token should be by default.'
        tokenAlphabet:
          type: text
          label: 'String of which the Token Generator can choose characters from.'
        KaomojiApp:
          type: boolean
          label: 'Use the VueJS app instead of a static block.'
